src/accounts/urls.py
from django.urls import path

from accounts import views

urlpatterns = [
    path('signup', views.Signup.as_view(), name='signup'),
]

src/catalogue/urls.py
from django.conf.urls import include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path


urlpatterns = [

    path("select2/", include("django_select2.urls")),
    path(
        '', include(
            ('teaching.urls', 'teaching'),
            namespace='teaching')
    ),

    path('accounts/', include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('pages/', include('django.contrib.flatpages.urls')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

src/teaching/urls.py
from django.urls import path, include
from django.views.generic import TemplateView
from rest_framework import routers
from . import views, api_views


router = routers.DefaultRouter()
router.register(r'course_material', api_views.CourseMaterialViewSet)
router.register(r'organization', api_views.OrganizationViewSet)


urlpatterns = [
    path('', views.LastCourseList.as_view(), name='index'),
    path('coursematerial', views.CourseMaterialList.as_view(), name='coursematerial-list'),
    path('coursematerial/pending', views.CourseMaterialPendingList.as_view(), name='coursematerial-pending-list'),
    path('coursematerial/<int:pk>', views.CourseMaterialDetail.as_view(), name='coursematerial-detail'),
    path('coursematerial/add', views.CourseMaterialCreateView.as_view(), name='coursematerial-create'),
    path('coursematerial/thanks', TemplateView.as_view(template_name="teaching/thanx.html"), name='coursematerial-thanx'),
    path('coursematerial/<int:pk>/edit', views.CourseMaterialUpdateView.as_view(), name='coursematerial-update'),
    path('coursematerial/<int:pk>/changestatus', views.CourseMaterialChangeStatusView.as_view(), name='coursematerial-change-status'),
    path('organization', views.OrganizationList.as_view(), name='organization-list'),
    path('organization/add', views.OrganizationCreateView.as_view(), name='organization-create'),
    path('organization/thanks', TemplateView.as_view(template_name="teaching/thanx.html"), name='organization-thanx'),
    path('organization/<int:pk>/edit', views.OrganizationUpdateView.as_view(), name='organization-update'),
]

urlpatterns += path('api/', include((router.urls, 'teaching'))),

src/teaching/forms.py
# Forms here
from django import forms
from django_select2 import forms as s2forms
from django.utils.translation import gettext as _
from teaching.models import CourseMaterial, Author, Organization, Tag, Format


class AuthorWidget(s2forms.ModelSelect2Widget):
    search_fields = [
        "name__icontains",
    ]


class OrganizationWidget(s2forms.ModelSelect2Widget):
    search_fields = [
        "name__icontains",
        "description__icontains",
    ]


class LicenseWidget(s2forms.ModelSelect2Widget):
    search_fields = [
        "code__icontains",
        "title__icontains",
    ]


class MultipleModelSelect2TagWidget(s2forms.ModelSelect2TagWidget):

    def build_attrs(self, base_attrs, extra_attrs=None):
        base_attrs = {
            "data-token-separators": '[","]',
        }
        return super().build_attrs(base_attrs, extra_attrs=extra_attrs)


class TagsWidget(MultipleModelSelect2TagWidget):
    queryset = Tag.objects.all()
    search_fields = [
        "label__icontains",
    ]

    def value_from_datadict(self, data, files, name):
        """Create objects for given non-pimary-key values. Return list of all primary keys."""
        values = super().value_from_datadict(data, files, name)
        if not values:
            return ''
        pk_values = [int(v) for v in values if v.isdigit()]
        pks = set()
        if pk_values:
            pks = self.queryset.filter(**{'pk__in': list(pk_values)}).values_list('pk', flat=True)
            pks = set(map(str, pks))
        cleaned_values = pk_values
        for val in set(values) - pks:
            cleaned_values.append(self.queryset.create(label=val).pk)
        return cleaned_values


class ContributorsWidget(MultipleModelSelect2TagWidget):
    queryset = Author.objects.all()
    search_fields = [
        "name__icontains",
    ]

    def value_from_datadict(self, data, files, name):
        """Create objects for given non-pimary-key values. Return list of all primary keys."""
        values = super().value_from_datadict(data, files, name)
        if not values:
            return ''
        pk_values = [int(v) for v in values if v.isdigit()]
        pks = set()
        if pk_values:
            pks = self.queryset.filter(**{'pk__in': list(pk_values)}).values_list('pk', flat=True)
            pks = set(map(str, pks))
        cleaned_values = pk_values
        for val in set(values) - pks:
            cleaned_values.append(self.queryset.create(name=val).pk)
        return cleaned_values


class CourseMaterialForm(forms.ModelForm):
    """CourseMaterial publish form"""

    new_author = forms.CharField(required=False,
                           label=_("Author name"),
                           help_text=_("Enter author name if not in the list"))

    new_orga = forms.CharField(required=False,
                         label=_("Organization name"),
                         help_text=_("Enter organization name if not in the list"))

    class Meta:
        model = CourseMaterial
        fields = ("course_url",
                  "title",
                  "description",
                  "format",
                  "level",
                  "tags",
                  "author",
                  "new_author",
                  "contributors",
                  "resource_license",
                  "organization",
                  "new_orga")
        widgets = {
            'author': AuthorWidget,
            'contributors': ContributorsWidget,
            'resource_license': LicenseWidget,
            'organization': OrganizationWidget,
            'tags': TagsWidget,
        }

    def clean_author(self):
        author_selected = self.cleaned_data['author']
        author_name = self.data.get('new_author', '')
        if author_name != "":
            new_author, created = Author.objects.get_or_create(name=author_name)
            return new_author
        return author_selected

    def clean_organization(self):
        orga_selected = self.cleaned_data['organization']
        orga_name = self.data.get('new_orga', '')
        if orga_name != "":
            new_orga, created = Organization.objects.get_or_create(name=orga_name)
            return new_orga
        return orga_selected


class CourseMaterialPublishForm(forms.ModelForm):
    """CourseMaterial publish form"""

    class Meta:
        model = CourseMaterial
        fields = ("status",)


class CreateResourceFromURLForm(forms.Form):
    """Get title from url form"""
    page_url = forms.URLField(label=_("Enter page URL"), required=False)


class CourseMaterialSearchForm(forms.Form):
    """CourseMaterial search form"""

    q_term = forms.CharField(
        label=_("Search in title and description"),
        required=False
    )
    q_tags = forms.MultipleChoiceField(
        label=_("Search in tags"),
        widget=s2forms.ModelSelect2MultipleWidget(
            model=Tag,
            search_fields=['label__icontains'],
        ),
        required=False,
    )
    q_format = forms.MultipleChoiceField(
        label=_("Search in tags"),
        widget=s2forms.ModelSelect2MultipleWidget(
            model=Format,
            search_fields=['label__icontains'],
        ),
        required=False,
    )
    q_published = forms.BooleanField(
        label=_("Published"),
        required=False,
    )

src/teaching/views.py
from django.urls import reverse_lazy
from django.conf import settings
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.contrib.sites.models import Site
from django.db.models import Q
from django.views.generic import ListView, DetailView
from django.views.generic.edit import CreateView, UpdateView

from teaching.models import CourseMaterial, Organization, Author, PublicationStatus, Tag
from teaching.forms import CourseMaterialForm, CourseMaterialPublishForm, CourseMaterialSearchForm, CreateResourceFromURLForm
from teaching.helpers import get_meta_from_url


class LastCourseList(ListView):
    """Homepage view"""
    model = CourseMaterial
    template_name = 'index.html'
    queryset = CourseMaterial.objects.filter(status=PublicationStatus.PUBLISHED).order_by('?')[:3]

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # Add title
        site_used = Site.objects.get(id=settings.SITE_ID)
        if hasattr(settings, 'SITE_TITLE') and settings.SITE_TITLE:
            context['homepage_title'] = settings.SITE_TITLE
        elif site_used:
            context['homepage_title'] = site_used.name

        # Inialize create from url form
        context['create_form'] = CreateResourceFromURLForm()
        return context


class CourseMaterialList(ListView):
    """CourseMaterial list view"""
    model = CourseMaterial

    def get_context_data(self, *, object_list=None, **kwargs):
        context_data = super().get_context_data(**kwargs)

        # Initialize search form
        initial_data = {}
        if 'q_term' in self.request.GET and self.request.GET.get('q_term') != '':
            initial_data['q_term'] = self.request.GET.get('q_term')
        if 'q_tags' in self.request.GET and self.request.GET.get('q_tags') != '':
            initial_data['q_tags'] = self.request.GET.get('q_tags')
        if 'q_format' in self.request.GET and self.request.GET.get('q_format') != '':
            initial_data['q_format'] = self.request.GET.get('q_format')
        if len(self.request.GET) == 0 or self.request.GET.get('q_published') == 'on':
            initial_data['q_published'] = True
        context_data['search_form'] = CourseMaterialSearchForm(initial=initial_data)

        # Inialize create from url form
        context_data['create_form'] = CreateResourceFromURLForm()
        return context_data

    def get_queryset(self):
        q_term = self.request.GET.get('q_term', '')
        queryset = CourseMaterial.objects.all()
        if self.request.GET.get('q_published') or len(self.request.GET) == 0:
            queryset = queryset.filter(status=PublicationStatus.PUBLISHED)
        if q_term:
            queryset = queryset.filter(
                Q(title__icontains=q_term) | Q(description__icontains=q_term)
            )
        q_tags = self.request.GET.get('q_tags', '')
        if q_tags:
            queryset = queryset.filter(tags__in=q_tags)
        q_format = self.request.GET.get('q_format', '')
        if q_format:
            queryset = queryset.filter(format__in=q_format)
        return queryset


class CourseMaterialPendingList(ListView):
    model = CourseMaterial
    template_name = "teaching/coursematerial_pending_list.html"
    queryset = CourseMaterial.objects.exclude(status=PublicationStatus.PUBLISHED)

    def get_context_data(self, **kwargs):
        context = super().get_context_data()
        context['form'] = CourseMaterialPublishForm()
        return context


class CourseMaterialDetail(DetailView):
    """CourseMaterial detail view"""
    model = CourseMaterial


class CourseMaterialCreateView(CreateView):
    """CourseMaterial create view"""
    model = CourseMaterial
    form_class = CourseMaterialForm
    template_name = 'teaching/coursematerial_form.html'
    success_url = reverse_lazy('teaching:coursematerial-thanx')

    def get_initial(self):
        """Set initial data from page_url in GET"""
        initial = super(CourseMaterialCreateView, self).get_initial()
        if 'page_url' in self.request.GET and self.request.GET.get('page_url') != "":
            try:
                page_url = CreateResourceFromURLForm().fields['page_url'].clean(self.request.GET.get('page_url'))
            except Exception:
                pass
            else:
                initial['course_url'] = page_url
                metas = get_meta_from_url(initial['course_url'])
                initial['title'] = metas['title']
                initial['description'] = metas['description']
        return initial


class CourseMaterialUpdateView(PermissionRequiredMixin, UpdateView):
    """CourseMaterial update view"""
    model = CourseMaterial
    permission_required = "teaching.change_coursematerial"
    form_class = CourseMaterialForm
    template_name = 'teaching/coursematerial_form.html'
    success_url = reverse_lazy('teaching:coursematerial-list')


class CourseMaterialChangeStatusView(PermissionRequiredMixin, UpdateView):
    """CourseMaterial change status view"""
    model = CourseMaterial
    permission_required = "teaching.change_coursematerial"
    form_class = CourseMaterialPublishForm
    success_url = reverse_lazy('teaching:coursematerial-pending-list')


class OrganizationList(ListView):
    """Organization list view"""
    model = Organization


class OrganizationCreateView(LoginRequiredMixin, CreateView):
    """Organization create view"""
    model = Organization
    fields = ("name", "description", "website", "contact_email", "address", "city")
    template_name = 'teaching/organization_form.html'
    success_url = reverse_lazy('teaching:organization-list')


class OrganizationUpdateView(PermissionRequiredMixin, UpdateView):
    """Organization create view"""
    model = Organization
    permission_required = "teaching.change_organization"
    fields = ("name", "description", "website", "contact_email", "address", "city")
    template_name = 'teaching/organization_form.html'
    success_url = reverse_lazy('teaching:organization-list')

src/teaching/templates/base.html
{% load static %}
{% load i18n %}

<!DOCTYPE html>
<html lang="en">
<head>

  <meta charset="UTF-8">
  <title>Ressources – {% block title %}{% endblock %}</title>
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <link rel="stylesheet" href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" />
  <link rel="stylesheet" href="{% static 'css/styles.css' %}" />

  {% block extra_head %}
  {% endblock %}

</head>
<body>

  {% block nav %}

  <nav class="navbar navbar-expand-md navbar-dark bg-blue">
    <a class="navbar-brand" href="{% url 'teaching:index' %}">{% trans "Home" %}</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarMain" aria-controls="navbarMain" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarMain">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item">
          <a class="nav-link" href="{% url 'teaching:coursematerial-list' %}">{% trans "Resources" %}</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'teaching:organization-list' %}">{% trans "Organizations" %}</a>
        </li>
      </ul>
      <ul class="navbar-nav">
        {% if user.is_anonymous %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'login' %}">{% trans "Login" %}</a>
        </li>
        {% else %}
        {% if user.is_staff %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'admin:index' %}">{% trans "Administration" %}</a>
        </li>
        {% endif %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'logout' %}">{% trans "Logout" %}</a>
        </li>
        {% endif %}
      </ul>
    </div>
  </nav>

  {% endblock %}

  <main id="content" class="{% block main-class %}container-fluid{% endblock %}">

    {% block content %}
    {% endblock %}

  </main>

  <footer id="footer" class="navbar navbar-light bg-light">
    {% block footer %}
    <a href="https://framagit.org/free-skool/teaching-catalogue/" target="_blank">
      {% trans "Source code" %}
    </a>
    <a href="/credits/">
      {% trans "Legal mentions and credits" %}
    </a>
    {% endblock %}
  </footer>

  <script src="{% static 'vendor/jquery-3.5.1.min.js' %}"></script>
  <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

  {% block extra_js %}
  {% endblock %}
</body>
</html>

src/teaching/templates/index.html
{% extends "base.html" %}
{% load i18n bootstrap4 %}

{% block title %}{% trans "Homepage" %}{% endblock %}

{% block main-class %}container{% endblock %}

{% block content %}
<h1>
    {% block h1 %}
    {% if homepage_title %}
        {{ homepage_title}}
    {% else %}
        {% trans "Course material catalogue" %}
    {% endif %}
    {% endblock %}
</h1>

{% block intro %}
{% endblock %}

<h2>{% trans "Three random resources" %}</h2>
<div class="row">

    {% for course in object_list %}
    <div class="col-sm-6 col-lg-4">
        <div class="card mb-3">
            {% include "teaching/_partials/course_card.html" %}
        </div>
    </div>
    {% endfor %}

</div>

<p class="text-center">
    <a class="btn btn-lg btn-brown" href="{% url 'teaching:coursematerial-list' %}">{% trans "See all resources" %}</a>
</p>

<p class="text-center">
  <a href="{% url 'teaching:coursematerial-pending-list' %}">&RightArrow; {% trans "Pending course material list" %}</a>
</p>


<form class="add-course-form" action="{% url 'teaching:coursematerial-create' %}" method="get">
    {% csrf_token %}
    <div class="form-inline justify-content-center">
        {% bootstrap_field create_form.page_url layout='inline' form_group_class='form-group mr-sm-2' %}
        <button class="btn btn-info" type="submit">
        {% trans "Add a resource" %}
        </button>
    </div>
</form>

{% endblock %}